### ISSUE TITLE
Does not work with Apache MQ 5.11

### ISSUE THREAD

**Issue by cmisztur** [knolleary/pubsubclient#61]
It looks like the library needs an overhaul to spec 3.1.1.

**Comment by cmisztur** [comment]
```
java.net.ProtocolException: Invalid CONNECT frame
	at org.fusesource.mqtt.codec.CONNECT.decode(CONNECT.java:91)[mqtt-client-1.10.jar:1.10]
	at org.apache.activemq.transport.mqtt.MQTTProtocolConverter.onMQTTCommand(MQTTProtocolConverter.java:195)[activemq-mqtt-5.11.1.jar:5.11.1]
	at org.apache.activemq.transport.mqtt.MQTTTransportFilter.onCommand(MQTTTransportFilter.java:94)[activemq-mqtt-5.11.1.jar:5.11.1]
	at org.apache.activemq.transport.TransportSupport.doConsume(TransportSupport.java:83)[activemq-client-5.11.1.jar:5.11.1]
	at org.apache.activemq.transport.tcp.TcpTransport.doRun(TcpTransport.java:214)[activemq-client-5.11.1.jar:5.11.1]
	at org.apache.activemq.transport.tcp.TcpTransport.run(TcpTransport.java:196)[activemq-client-5.11.1.jar:5.11.1]
	at java.lang.Thread.run(Unknown Source)[:1.8.0_40]
```

**Comment by knolleary** [comment]
Correct - this library currently only supports 3.1

**Comment by q2dg** [comment]
Are there any plans to support it? This library seems a little forgotten looking at last commits...
Thanks, anyway

**Comment by knolleary** [comment]
@q2dg  the lack of commits is more a reflection of stability (for my uses) than abandonment. But I do recognise support for 3.1.1 is overdue, so will try to get something done in the near future.

**Comment by q2dg** [comment]
@knolleary Thanks

**Comment by jschuryk** [comment]
I was able to get publishing working with Mosquitto 3.1.1 however subscribing doesn't seem to be working.

**Comment by knolleary** [comment]
3.1.1 support added last night. Some more testing to be done, but expect a new release this week.

**Comment by q2dg** [comment]
Yeah!!! Thanks!!!
